import type { Address, TokenReserve, VaultFeeReceipt } from '@nftx/types';

export type Position = {
  vaultId: string;
  vaultAddress: Address;
  poolId: Address;
  liquidityEth: bigint;
  inventoryValue: bigint;
  liquidityValue: bigint;
  inventoryTokens: bigint;
  liquidityTokens: bigint;
  inventoryShare: bigint;
  liquidityShare: bigint;
  inventoryApr: number;
  liquidityApr: number;
  inventorySplit: number;
  liquiditySplit: number;
  claimableAmount: bigint;
  valueStaked: bigint;
  claimableValue: bigint;
  totalValue: bigint;
  poolReserves: TokenReserve;
  xToken: bigint;
  xTokenSupply: bigint;
  xTokenShare: bigint;
  xSlp: bigint;
  xSlpSupply: bigint;
  slpBalance: bigint;
  slpSupply: bigint;
  feeReceipts: VaultFeeReceipt[];
  createdAt: number;
};
