import type { BigNumber } from '@ethersproject/bignumber';
import type { TokenReserve, VaultFeeReceipt } from '@nftx/types';

export type Position = {
  vaultId: string;
  vaultAddress: string;
  poolId: string;
  liquidityEth: BigNumber;
  inventoryValue: BigNumber;
  liquidityValue: BigNumber;
  inventoryTokens: BigNumber;
  liquidityTokens: BigNumber;
  inventoryShare: BigNumber;
  liquidityShare: BigNumber;
  inventoryApr: number;
  liquidityApr: number;
  inventorySplit: number;
  liquiditySplit: number;
  claimableAmount: BigNumber;
  valueStaked: BigNumber;
  claimableValue: BigNumber;
  totalValue: BigNumber;
  poolReserves: TokenReserve;
  xToken: BigNumber;
  xTokenSupply: BigNumber;
  xTokenShare: BigNumber;
  xSlp: BigNumber;
  xSlpSupply: BigNumber;
  slpBalance: BigNumber;
  slpSupply: BigNumber;
  feeReceipts: VaultFeeReceipt[];
  createdAt: number;
};
